### ISSUE TITLE
Add the pod!

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.4-portfolio#13]
Currently, then repository has members of the MLH team on it, but you should replace them with members of the pod.

You can update information in `_data/fellows.yml`

You should work on:
- [ ] Replacing the images
- [ ] Update the names and locations of each fellow
- [ ] Update the pod number inside of `_config.yml`

**Comment by Pratyush1606** [comment]
@wrussell1999 Can you please assign this issue to me and @shravani05? Actually, we will be working on issue #9 and before that closing, this issue will be good.

**Comment by wrussell1999** [comment]
Done!

**Comment by NoahCardoza** [comment]
How is this coming along? I'd like to get this merged before #23 so it can use the data you'll be collecting from the Pod Tracker.

**Comment by shravani05** [comment]
@NoahCardoza we will make a pr as soon as we get data from all the pod mates.
