### ISSUE TITLE
Deprecated command in setup section of documentation

### ISSUE THREAD

**Issue by obasekiosa** [MLH-Fellowship/pod-4.1.4-portfolio#17]
Currently to set up the project locally the following command is used.
`bundle install --path vendor/bundle`

Using the `--path` flag with the install command is being deprecated in future versions of bundler. (See below)
[official documentation](https://bundler.io/man/bundle-config.1.html#REMEMBERING-OPTIONS)

![image](https://user-images.githubusercontent.com/12957252/140924030-8c25551b-c7fb-4647-8a5d-2642aa055dcf.png)

This should be updated to reflect the recommended alternative.

`bundle config set --local path 'vendor/bundle' && bundle install`

**Comment by NoahCardoza** [comment]
@obasekiosa Do you want to take this issue?

**Comment by obasekiosa** [comment]
> @obasekiosa Do you and your teammate want to take this issue?

yes, I and @helenduz  would like to take this issue.
