### ISSUE TITLE
Improve loading time for images

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.4-portfolio#2]
Currently, images take a while to load as they're quite large. Can we compress the images when they are committed using a GitHub action to improve loading speeds?

**Comment by rajat2502** [comment]
Hey @wrussell1999, can you please assign this issue to our team? @Sargam-Agarwal and I would like to work on it.

**Comment by wrussell1999** [comment]
Done @rajat2502! Next time, ask @NoahCardoza to help here 💯

**Comment by rajat2502** [comment]
Thanks, @wrussell1999, sure, will keep that in mind from next time :)
