### ISSUE TITLE
Fix leaderboard in dark mode

### ISSUE THREAD

**Issue by NoahCardoza** [MLH-Fellowship/pod-4.1.4-portfolio#32]
After merging both the leaderboard and dark mode PR we are getting some interesting results:

![image](https://user-images.githubusercontent.com/10343470/141490517-ab23957c-26ed-4a11-81df-e089562047c4.png)

I think the white rows should become a shade of grey? Any ideas?

**Comment by obasekiosa** [comment]
I also think the black text should be white or another colour that contrasts the background colour better.

I and @helenduz noticed this yesterday and would like to work on it once we are done creating the PR for our current tasks.
