### ISSUE TITLE
Add pod blog

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.4-portfolio#7]
It would be awesome to add a blog feature to this repository where fellows can share their insights and people can tune in!

**Comment by dhwaj1902** [comment]
@NoahCardoza I would like to work on this issue.

**Comment by dhwaj1902** [comment]
> @dhwaj1902 Who is your teammate?

Its @EkjotKaur

**Comment by NoahCardoza** [comment]
Perfect! I assigned them as well!
