### ISSUE TITLE
Profile page for each fellow

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.4-portfolio#9]
When you click on each fellows card, it sends you to a separate page which includes more detail such as:

- Description
- Favourite programming languages
- Interests outside of technology
- University

**Comment by Pratyush1606** [comment]
Hello @wrussell1999, I and @shravani05 want to work on this issue. Can you please assign our team to this issue?

**Comment by wrussell1999** [comment]
Done @Pratyush1606! In future, work with @NoahCardoza to get assigned 💯

**Comment by NoahCardoza** [comment]
How is this coming along? I'd like to get this merged before #23 so it can use the data you'll be collecting from the Pod Tracker.
